### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by KaroliinaPilden** [sanderrandmets/VR#18]
Controlside kindlaksmääramine, panna kirja, mis nuppude taga toimub mingi tegevus.

**Comment by razexay** [comment]
Kirjutasin vastused Word faili
[Basic controls.docx](https://github.com/sanderrandmets/VR/files/3012288/Basic.controls.docx)

**Comment by razexay** [comment]
Lisan lingi, mille abil saab rakendusse lisada 6DoF controlleri.
https://github.com/aframevr/aframe/blob/master/docs/introduction/interactions-and-controllers.md
