### ISSUE TITLE
Õpetaja küsimused

### ISSUE THREAD

**Issue by KaroliinaPilden** [sanderrandmets/VR#20]
1. Õpetaja küsimuste välja mõtlemine.
2. Kui õpetaja liigub õpilase ette, kuvatakse õpilasele interaktiivne aken, kus on kirjas küsimus, all on võimalikud vastusevariandid ja jookseb interaktiivne taimer.
3. Õpetaja portree on liikumatult antud küsimuste taustal.

**Comment by Fmummy** [comment]
[Küsimused.docx](https://github.com/sanderrandmets/VR/files/3033477/Kusimused.docx)

**Comment by Fmummy** [comment]
[Õpetaja küsimused.docx](https://github.com/sanderrandmets/VR/files/3033488/Opetaja.kusimused.docx)

**Comment by KaroliinaPilden** [comment]
1.	Kas sul kodutöö on tehtud?
2.	Miks sul kodutöö tegemata on?/Kas kodutöö oli raske?
3.	Millal kirjandi ära lõpetad?
4.	Kas sa konsultatsiooni vajadusel tuled?
5.	Kes on süüdi kui sinu hinded halvad on?

**Comment by Fmummy** [comment]
6.Millal sa järelvastamisele tulla saad?
