### ISSUE TITLE
Õpilase vastused

### ISSUE THREAD

**Issue by KaroliinaPilden** [sanderrandmets/VR#21]
Õpilase vastuste välja mõtlemine.

**Comment by Fmummy** [comment]
[Õpilase vastused.docx](https://github.com/sanderrandmets/VR/files/3033554/Opilase.vastused.docx)

**Comment by Fmummy** [comment]
[Õpilase vastused (1).docx](https://github.com/sanderrandmets/VR/files/3033925/Opilase.vastused.1.docx)
