### ISSUE TITLE
Dialoogid

### ISSUE THREAD

**Issue by KaroliinaPilden** [sanderrandmets/VR#22]
Dialoogide kokku panemine. Dialoogide arv on veel lahtine.

**Comment by Fmummy** [comment]
[DIALOOG.docx](https://github.com/sanderrandmets/VR/files/3043021/DIALOOG.docx)

**Comment by KaroliinaPilden** [comment]
[DIALOOG.docx](https://github.com/sanderrandmets/VR/files/3043038/DIALOOG.docx)
