### ISSUE TITLE
Riiulite disain

### ISSUE THREAD

**Issue by KaroliinaPilden** [sanderrandmets/VR#4]
Riiulite disainimine A-frame's.

**Comment by sanderrandmets** [comment]
<!DOCTYPE html>
<html>
  <head>
    <title>Hello, WebVR! - A-Frame</title>
    <meta name="description" content="Hello, WebVR! - A-Frame">
    <script src="https://aframe.io/releases/0.5.0/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>
      <a-entity position="-1 0.5 -3" >
      <a-box position="0 -0.7 0" src="https://cdn.glitch.com/916aaa97-067a-44be-a789-8f47d485fc0a%2FAllalaaditud%20fail.jpg?1553502894591" rotation="0 0 0" width="2" depth="1" height="0.1" ></a-box>
        <a-box position="-1 0 0" rotation="0 0 90"  src="https://cdn.glitch.com/916aaa97-067a-44be-a789-8f47d485fc0a%2FAllalaaditud%20fail.jpg?1553502894591" width="1.5" depth="1" height="0.1" ></a-box>
        <a-box position="1 0 0" rotation="-0 0 90" src="https://cdn.glitch.com/916aaa97-067a-44be-a789-8f47d485fc0a%2FAllalaaditud%20fail.jpg?1553502894591" width="1.5" depth="1" height="0.1" ></a-box>
      <a-box position="0 0.7 0" src="https://cdn.glitch.com/916aaa97-067a-44be-a789-8f47d485fc0a%2FAllalaaditud%20fail.jpg?1553502894591" rotation="0 0 0" width="2" depth="1" height="0.1" length="" ></a-box>
        <a-box position="-1 1 0" rotation="0 0 90"  src="https://cdn.glitch.com/916aaa97-067a-44be-a789-8f47d485fc0a%2FAllalaaditud%20fail.jpg?1553502894591" width="1.5" depth="1" height="0.1" ></a-box>
        <a-box position="1 1 0" rotation="0 0 90"  src="https://cdn.glitch.com/916aaa97-067a-44be-a789-8f47d485fc0a%2FAllalaaditud%20fail.jpg?1553502894591" width="1.5" depth="1" height="0.1" ></a-box>
      <a-box position="0 1.7 0" src="https://cdn.glitch.com/916aaa97-067a-44be-a789-8f47d485fc0a%2FAllalaaditud%20fail.jpg?1553502894591" rotation="0 0 0" width="2" depth="1" height="0.1" length="" ></a-box>
    </a-entity>
      
     
      
      
    </a-scene>
  </body>
</html>

**Comment by KaroliinaPilden** [comment]
Kood lisatud failina.
